[package]
name = "rust_lox"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
thiserror = "2.0.11"
ast_macro = { path = "ast_macro" }
regex = "1.11.1"
test-generator = "0.3.1"
